### ISSUE TITLE
 Missing analysis for base commit...

### ISSUE THREAD

**Issue by myoung34** [github/codeql-action#104]
Im testing out the new feature, but my PR's are showing [this](https://github.com/myoung34/tilty/pull/13): `Code scanning / CodeQL Completed in 2s — Missing analysis for base commit 8fbde843b5a06db9299c8df42f299cd8bd3c9b1f` (more info [here](https://github.com/myoung34/tilty/pull/13/checks?check_run_id=846009893) )

this is strange because i set up and scanned that commit (PR to master making it a base): https://github.com/myoung34/tilty/commit/8fbde843b5a06db9299c8df42f299cd8bd3c9b1f

which shows that it found no new alerts: https://github.com/myoung34/tilty/runs/845768407 for that git SHA

**Comment by marcogario** [comment]
:wave: Thanks for reporting this! 

The message appears because (in addition to the commit oid) we consider a few more parameters when comparing results. In particular, we use a combination of workflow+job when matching analyses, because different jobs can setup the code in very different ways. In this case, the commit (8fbde84) was only analyzed via the `deploy.yml:test` job, but the branch is not running that job. Similarly, the branch is being analyzed via `tests.yml:test` but master is not.

If possible, you should have at least one configuration where you run both the source and the target of a PR.

On our end, we will try to include more details in the error message.

**Comment by myoung34** [comment]
> but the branch is not running that job.

Im not sure I follow.
What can I do on my end to get PR's to not show `Missing analysis for...` ? Sorry for the back and forth, this area of GH is obviously very new to me (beta and all)

**Comment by marcogario** [comment]
For example, you could change your `deploy.yml` workflow to run on pull-requests that target master by adding 

```
on: 
  pull_request: master
```

so that the analysis defined in your `test` job would run both on master (because you run it on push) and on all branches that target master. 

Alternatively, you could remove the ignore from the `tests.yml`:
```
     branches-ignore:	    
      - 'master'
```

Basically you want at least one of the workflows to apply to both the branches and master.

**Comment by myoung34** [comment]
Alright @marcogario I refactored that and it seems fixed, Ill close and open a new one to scope a new question.

Thanks!

**Comment by josueetcom** [comment]
I seem to be experiencing this even though I trigger CodeQL on the `main` branch for both pull requests and pushes from the [same workflow job](https://github.com/beyondhb1079/s4us/blob/main/.github/workflows/codeql-analysis.yml#L3-L10).

My latest PR's **GitHub Code Scanning / ESLint** job says ["Missing analysis for base commit bf4aa1f2ecf01cfdbd6124eafe26f9195cbf7c08"](https://github.com/beyondhb1079/s4us/pull/75/checks?check_run_id=1234468597) but the [supposed missing analysis for that commit](https://github.com/beyondhb1079/s4us/runs/1207905080) seems to have run successfully.

Am I missing something?

**Comment by robertbrignull** [comment]
The missing analysis is for ESLint coming from the ossar action instead of from CodeQL, however it looks like that was also run on the same commit as the same time as CodeQL so I can't quite see why it would be missing. Is this happening repeatedly or is it a one-off bug?

**Comment by josueetcom** [comment]
It seems like it might be a one off bug, PRs no longer seem to have the issue. Thanks
