### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by semihalev** [github/codeql-action#110]
While initialisation action stopped with error `Rate Limit Exceeded` from github API. I looked deep inside but I didn't find any problem. 

Report: https://github.com/semihalev/sdns/runs/865352547?check_suite_focus=true

How can i solve that problem?

Thanks.

**Comment by robertbrignull** [comment]
Apologies for that error message as it's not correct. We'll get that sorted out so it is more informative.

The actual problem is that your repository has not yet been enrolled into the code scanning beta. I can see you on the waiting list, and enrollments are happening constantly as we slowly ramp up, so you should be in within a few weeks.

I'll close this issue for now but let me know if you have other questions.

**Comment by agius** [comment]
I'm getting the same issue, though I'm only running the `github/codeql-action/init@v1` action. I'm trying to develop a Ruby extractor & library for CodeQL, and need to run the `codeql` CLI as part of integration testing. So probably I don't need to enable the code scanning UI & enterprise features for [the codeql_ruby repo](https://github.com/agius/codeql_ruby). I just wanted to use the `github/codeql-action/init@v1` to set up the CLI on the Action runner.

@robertbrignull should I sign up for the code scanning beta anyway, or is there some other way to get around the rate limiting? Maybe just `curl` and `tar -x` the binaries in my build script without using the action?

[Github Action results](https://github.com/agius/codeql_ruby/pull/2/checks?check_run_id=878205756#step:4:50) - [Archived as a gist for posterity](https://gist.github.com/agius/0a2fdc859fbbcb0f991ad8f79388abb2)

**Comment by robertbrignull** [comment]
The action makes calls to the GitHub API throughout that require being enrolled in code scanning, so you'll need to be in the beta to use it at all.

As you've pointed out though that doesn't stop you from using CodeQL on your own and for testing https://github.com/agius/codeql_ruby you'll probably be better off downloading the CLI binaries from https://github.com/github/codeql-cli-binaries/releases directly. The bundle that the codeql-action downloads is significantly larger because it contains compiled queries for all the other languages and you don't need any of those.
