### ISSUE TITLE
`Test Python Package Installation` tests are flaky

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql-action#1122]
These tests often fail for external reasons. We should add some sort of retry on failure for these tests.

**Comment by aeisenberg** [comment]
On a deeper look, this is not a flaky test, it is just failing. Python2 + poetry is not a combination that can be easily supported. Best suggestion is to remove that combination and state that we can't run on it.

More information: https://github.com/actions/setup-python/issues/374

**Comment by RasmusWL** [comment]
I looked over https://github.com/actions/setup-python/issues/374 a bit, and I don't think that's the _cause_ of it, since we're not using the `setup-python` action in those tests at all.

Instead I think we're running into a similar problem, the poetry installation (under Python 3) on windows is not able to find the Python 2 executable.

From the [logs of a failure](https://github.com/github/codeql-action/runs/7044390284?check_suite_focus=true).

```
Found poetry.lock, will install packages with poetry
+ C:\hostedtoolcache\windows\Python\3.10.5\x64\python.exe -m poetry install --no-root
...
The currently activated Python version 3.10.5 is not supported by the project (^2.7).
Trying to find and use a compatible version. 
  NoCompatiblePythonVersionFound
  Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```

**Comment by aeisenberg** [comment]
Right, I don't think it is caused by https://github.com/actions/setup-python/issues/374, but it is the same underlying issue. Thanks for taking a deeper look here.
