### ISSUE TITLE
Action results in two checks on a PR, one that passes, one that fails

### ISSUE THREAD

**Issue by Scotchester** [github/codeql-action#122]
Hi folks, thanks for all your hard work on this tool.

I'm hoping someone can help me understand why when I set this action up to run on PRs (following the basic setup instructions), I end up getting _two_ checks on the PR. Actually, only one shows up at first, titled "Code scanning - action / CodeQL-Build (pull_request)". It seems to do the bulk of the scanning, since it takes a little over 10 minutes on our repo. Once it completes, it is marked passing, but then a second check appears farther down the list of checks, titled "Code scanning / CodeQL", which completes in 2 seconds, and it fails (as expected, since I am testing the action with the introduction of code I expected to fail the scan).

You can see this in action on cfpb/cfgov-refresh#5870.

Why are there two checks? Why does one of them pass? Have I misconfigured something?

Thanks for your time.

**Comment by robertbrignull** [comment]
This is working as expected, but perhaps it's not too clear. The action titled "Code scanning-action / CodeQL-build" is the workflow you wrote and is the one doing the analysis of your project. Once that analysis is submitted GitHub compares it with an analysis submitted for the branch you are merging into, because otherwise how would we know which alerts are new and which are existing ones. In this case there are alerts introduced by this PR and we create a new check called "Code scanning / CodeQL" to show you these new alerts.

Some details like the "completed in" time for the second check are a bit meaningless, so best not to worry about those. Bottom line is you're not doing anything wrong.

I'll close this issue for now but let me know if you'd like any more explanation.

**Comment by Scotchester** [comment]
Thanks, @robertbrignull, that helps clear things up a bit.

I'm wondering if it would be possible to incorporate the comparison check into the scan check? If there is a user benefit to seeing them as separate checks, I'm not understanding what that is.

If that's not possible, perhaps I could suggest:
1. Renaming the 2nd action that shows the alerts to something like "Code scan comparison results" or just "Code scan results" or something like that?
2. Updating the docs (the [Enabling Code Scanning](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning) page, specifically) to describe that this is the expected behavior for PR checks

Thanks again!

**Comment by robertbrignull** [comment]
> I'm wondering if it would be possible to incorporate the comparison check into the scan check?

Unfortunately it's not that easy. The main problem is that the analyses of the PR and of the base branch could happen in any order. So if the PR analysis happens first then there won't be anything to compare against when it finishes.

> If that's not possible, perhaps I could suggest:
> 1) Renaming the 2nd action that shows the alerts to something like "Code scan comparison results" or just "Code scan results" or something like that?
> 2) Updating the docs (the Enabling Code Scanning page, specifically) to describe that this is the expected behavior for PR checks

Those are pretty reasonable suggestions. I'll create issues internally and see if we can get the naming or the documentation made more clear.

**Comment by Scotchester** [comment]
Sounds good! Thanks, Robert.
