### ISSUE TITLE
Regression "Cannot read properties of undefined (reading 'java')" at uploadTrapCaches

### ISSUE THREAD

**Issue by johannes-riecken** [github/codeql-action#1222]
Some of my Java pipelines that used to work (e.g. [this one](https://github.com/johannes-riecken/mailman/runs/8096089895?check_suite_focus=true)) now fail. Apart from the error in the title and the stacktrace I don't see other errors in the logs.

The error message I get is:

```
Uploading results

/opt/hostedtoolcache/CodeQL/0.0.0-20220421/x64/codeql/codeql database bundle /home/runner/work/_temp/codeql_databases/java --output=/home/runner/work/_temp/codeql_databases/java.zip --name=java
Creating bundle metadata for /home/runner/work/_temp/codeql_databases/java...
Creating zip file at /home/runner/work/_temp/codeql_databases/java.zip.
Error: Cannot read properties of undefined (reading 'java')
TypeError: Cannot read properties of undefined (reading 'java')
    at uploadTrapCaches (/home/runner/work/_actions/github/codeql-action/v2/lib/trap-caching.js:126:43)
    at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:129:31)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:176:9)
```

**Comment by edoardopirovano** [comment]
Greetings! Many thanks for reaching out to us with this issue. The problem here is that your workflow specifies version `@v2.1.9` in the `init` step but uses `@v2` in the `analyze` step. Having mismatched versions of the different steps in a CodeQL workflow is not a configuration we support, and we generally recommend using the same version for all the steps. I believe if you either change the `init` step to also use `@v2` or, conversely, change the other steps to also use `@v2.1.9` then your workflow should work again. The former is the solution I would personally recommend, as it will ensure you keep getting updates to CodeQL. If you prefer to not get updates and keep a version pinned, however, the latter is also an option.

**Comment by johannes-riecken** [comment]
Hey Edoardo, yes that did the trick, thanks for the quick reply!

**Comment by edoardopirovano** [comment]
Perfect, glad your issue is resolved!
