### ISSUE TITLE
Init somehow interferes with .NET SDK

### ISSUE THREAD

**Issue by leastprivilege** [github/codeql-action#1312]
2 weeks ago all CodeQL actions in all our various repos started failing (also repos that haven't been updated and codeql was triggered via a cron)

https://github.com/duendesoftware
https://github.com/IdentityModel

Our build [script](https://github.com/DuendeSoftware/IdentityServer/blob/dom/code-ql-experiments/build.sh) suddenly always fails if run after codeql init.

I have finally narrowed it down in this action definition - we do

1. install the .NET SDK
2. run the build script (**works**)
3. run codeql init
4. run the same build script again (**fails**)

I also added some dotnet info in between.

https://github.com/DuendeSoftware/IdentityServer/actions/runs/3273133383/jobs/5384969932

Is this a known problem somehow? Because we really do not know what cause all those problems.

**Comment by tausbn** [comment]
Thank you for your report!

This is due to a bug in our build tracing that was recently introduced. Luckily, it was also fixed recently, but the fix has yet to land in the stable release of the CodeQL action.

In the short term, you should be able to add the option `tools: latest` for the `github/codeql-action/init` step, and that should make the problem go away.

**Comment by leastprivilege** [comment]
sigh. thanks.

**Comment by leastprivilege** [comment]
OK. I can confirm that the fixes the problem. thanks again.

**Comment by tausbn** [comment]
I'm glad it worked out, and I apologise for the disruption. 🙂 

Hopefully the fix should get released officially in version 2.11.2 in a few weeks time. At that point you no longer need to use the `latest` version.
