### ISSUE TITLE
support scan-build sarif output

### ISSUE THREAD

**Issue by Trass3r** [github/codeql-action#1381]
https://github.com/github/codeql-action/issues/220#issuecomment-1311464236
scan-build produces 1 sarif file per source file which results in errors about uploading more than 15 runs, even though most are empty.

It can be mitigated a bit via
```sh
npx -y @microsoft/sarif-multitool merge csa/*/*.sarif
```

**Comment by Trass3r** [comment]
It looks like it: https://github.com/Trass3r/llvm-project/actions/runs/3512494173/jobs/5884251411
Fail example: https://github.com/Trass3r/llvm-project/actions/runs/3491551485/jobs/5844321747
```
Error: Code Scanning could not process the submitted SARIF file:
  rejecting SARIF, as there are more runs than allowed (2726 > 15)
  Error: Code Scanning could not process the submitted SARIF file:
  rejecting SARIF, as there are more runs than allowed (2726 > 15)
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/main/lib/upload-lib.js:312:19)
      at async run (/home/runner/work/_actions/github/codeql-action/main/lib/upload-sarif-action.js:55:13)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/main/lib/upload-sarif-action.js:70:9)
```

**Comment by aeisenberg** [comment]
Thanks for describing. This looks like a reasonable workaround. Can you explain what is missing?

**Comment by Trass3r** [comment]
Well couldn't the action use a better limit based on actual complexity or file size rather than simply the number of sarif files? As I mentioned in a normal run most of these are "empty".

**Comment by aeisenberg** [comment]
There are already multiple kinds of restrictions: path complexity, number of runs, number of alerts, and file size, to name a few. These restrictions are put in place by the code scanning server to avoid processing degenerate or malicious uploads. 

In all cases, these limits were determined using heuristics based on our experience of SARIF files being uploaded in the wild. Because these heuristics are not 100% perfect doesn't mean they are unhelpful. We rarely see legitimate SARIF uploads that break these limits and when we do, we work hard to ensure that these uploads change so they are acceptible.

It's unfortunate that your upload initially breached one of our restrictions, but because you have found a workaround, I don't see there is anything more for our team to do.
