### ISSUE TITLE
CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled

### ISSUE THREAD

**Issue by char0n** [github/codeql-action#1528]
Hello,

My CodeQL analysis suddenly stopped working in following run: https://github.com/swagger-api/apidom/actions/runs/4112641841/jobs/7098389969#step:4:8259

It **fails** specifically on:

![image](https://user-images.githubusercontent.com/193286/217330546-a13cc377-7c42-4f6e-a1aa-dc6720ebe477.png)

and says following: `CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled`.

I'm using advanced setup and custom `codeql.yaml` workflow file. I've consulted https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow and determined that I don't have default setup enabled. 

Here is my code scanning settings:

![image](https://user-images.githubusercontent.com/193286/217330033-c74ac350-f194-446b-bf9a-942b3b65b4a7.png)

I'm really now sure at this point what is happening and how to get CodeQL working. I've tried to disable and re-enable the workflow, deleted the workflow file and re-created it again. Interesting about this is that CodeQL in PRs is working, but it just doesn't work on `main` branch.

Any advice please?

**Comment by marcogario** [comment]
:wave: @char0n for the report! :heart: This has highlighted a bug that was recently introduced. We are working on a fix.

**Comment by marcogario** [comment]
This should be fixed now, please let me know if it is not the case, otherwise, feel free to close the issue. Thank you!

**Comment by char0n** [comment]
Yep, I can confirm, everything now works as expected. Thank you!

**Comment by aravindvnair99** [comment]
@marcogario Looks like the bug is not fully resolved if you look at https://github.com/anmol098/waka-readme-stats/pull/387

@char0n do you mind re-opening this ticket?

**Comment by MPParsley** [comment]
This issue hasn't been resolved, see https://github.com/StadGent/node_service_adlib-backend/pull/97

https://github.com/StadGent/node_service_adlib-backend/actions/runs/4419164254/jobs/7747694733

**Comment by char0n** [comment]
@aravindvnair99 all right, I'm reopening, but as I mentioned in https://github.com/github/codeql-action/issues/1528#issuecomment-1422280604, it has been resolved for me.

**Comment by MPParsley** [comment]
Same issue here: https://github.com/StadGent/node_service_adlib-backend/pull/104

**Comment by marcogario** [comment]
:wave:  @MPParsley  Thanks for the feedback.

Please note that it is intentional that you are not able to run both an analysis via an advanced configuration and default setup, you can only run one of the two. If you want to continue using default setup, please either delete the yml workflow file or disable it.

The original issue reported here was due to a bug that *even when default setup was disabled* the yml upload was being rejected.  I will change the title of the issue to make this more clear.

We are working on improving the flow for converting from advanced to default , so that hopefully things are smoother here.

I will close the issue, but feel free to re-open it and provide more information, if this does not clarify.
