### ISSUE TITLE
Java: how do I specify a Gradle version?

### ISSUE THREAD

**Issue by trevorgerhardt** [github/codeql-action#1574]
Gradle recently released v8 and we'd like to stay on version v7. How do I specify a Gradle version while using this plugin?

This may be a Java/Gradle issue, but I couldn't figure out where this was getting configured for GitHub Actions.

**Comment by smowton** [comment]
The preferred way is to commit the Gradle Wrapper to your repo (https://docs.gradle.org/current/userguide/gradle_wrapper.html) -- that way code scanning and any other build environment will fetch and use your preferred Gradle version instead of whatever the latest Github Actions image happens to ship (which as you noticed recently incremented to Gradle 8).

**Comment by trevorgerhardt** [comment]
That's exactly what I was looking for @smowton, thanks!
