### ISSUE TITLE
Provide a solution to resolve 3rd party alerts .

### ISSUE THREAD

**Issue by Subharanjan2055** [github/codeql-action#1627]
Hi 
In my project i am getting so many alerts which comes from 3rd party lib files . So since it is  high & medium severity  i dont want to make those alerts as false possitive . Does anyone have work on these lib if yes please let me know the solutions that you implemented to resolve those Alerts . Even i also upgrade those lib version to latest .

PFA lib name & Version

jquery.dataTables.js	-V1.13.4
bootstrap-datepicker.js-	V 1.9.0
JqueryFormAjaxFileUpload.js  -V4.3.0
bootstrap.js  -V5.3
bootstrap-table.js	 -V1.21.3

**Comment by aeisenberg** [comment]
The fact that code scanning is finding alerts in these libraries means that these libraries are being added to the database. I would need to see your workflow file to be sure, but you would need to ensure that these libraries are not included when you build the database. There are several ways to do this:

1. Avoid running npm install before the `init` step (assuming that these libraries are installed through npm)
2. Delete the files before running `init`
3. Add a [`paths-ignore` property to your codeql config file](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#specifying-directories-to-scan).

I'd recommend the third option, but the first two migth work as well.

**Comment by Subharanjan2055** [comment]
@aeisenberg what if i dont want to ignore those files to be scanned is their any solution to resolve those alerts . I am using standard codeql workflow and in config files am using -uses: security-extended

**Comment by Subharanjan2055** [comment]
@aeisenberg any update on this ?

**Comment by aeisenberg** [comment]
I'm not sure what you're asking about here. Our recommendation is to avoid scanning third party libraries since you don't really have control over them. You are using `security-extended`, which is much more likely to show false positives than our default query suite, so it is not surprising that you are seeing alerts. Many of them are likely false positives. If you like, you can raise PRs in the repos that have some of these alerts, but before you do, you should take a look and ensure that they are indeed true positives.

**Comment by aeisenberg** [comment]
Closing this issue for now. Feel free to re-open if you have any more questions.
