### ISSUE TITLE
Codeql-action/init - Support for overwrite flag

### ISSUE THREAD

**Issue by rseeton** [github/codeql-action#1683]
CodeQL has added an '-override' flag to the options list which will force the deletion of an existing database.  https://github.com/github/codeql-cli-binaries/issues/44
We hit this issue intermittently on our hosted runners (the persistent runners are cleaned on a schedule - if you are unlucky, you will attempt a CodeQL run on an instance that has not yet been cleaned).

To get around this, we would like to use the -override function in our GitHub - however this does not appear to be a supported option in the github/codeql-action/init action.

Can we get 'overwrited' option added to the init action?

**Comment by aeisenberg** [comment]
Thank you for raising this issue. Our recommendation is that for self-hosted runners you include a `clean` step after running the `init` step. In this step, you would perform any cleanup like deleting old databases, old checkouts, or any other state.

However, there is an alternative approach. There is a [cli config file](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/specifying-command-options-in-a-codeql-configuration-file#using-a-codeql-configuration-file) that you can create and add the non-standard options, like the `--overwrite` flag. 

We generally prefer using a `clean` step since gives you the option to remove all state, instead of just previous databases.

**Comment by rseeton** [comment]
@aeisenberg  - Hmmm... a clean step is a option, but it is a larger hammer than I had hoped to use.  

As the cli config file is located in the $HOME directory ($HOME/.config/codeql/config) I assume it needs to be defined on the self-hosted runner setup and would not be able to easily reference it from the repository that contains the workflow with the codeql-init action.

Thanks

**Comment by aeisenberg** [comment]
> As the cli config file is located in the $HOME directory ($HOME/.config/codeql/config) I assume it needs to be defined on the self-hosted runner setup and would not be able to easily reference it from the repository that contains the workflow with the codeql-init action.

That is correct. On reflection, I would recommend using the `CODEQL_ACTION_EXTRA_OPTIONS` env var.

**Comment by rseeton** [comment]
Ah!  The secret ways :) 

Excellent, thanks @aeisenberg  - I'll try it with the CODEQL_ACTION_EXTRA_OPTIONS approach.  
The Action without throwing a warning with this env setting and it appears to be picked up correctly in the run.

We can close this out - if I have further issues, I'll open a new issue.
Regards.
