### ISSUE TITLE
Dotnet 8 Support

### ISSUE THREAD

**Issue by alex289** [github/codeql-action#1996]
Dotnet 8 just came out yesterday and after migrating my project the codeql workflow autobuild fails:
https://github.com/alex289/CleanArchitecture/actions/runs/6874722441

The [docs](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/) also don't list dotnet 8 as supported

**Comment by mbg** [comment]
Hi @alex289 👋 

As you note, .NET 8 / C# 12 were only released yesterday and it generally requires a bunch of work on our end to support new language versions. You can keep an eye on our [public roadmap](https://github.com/orgs/github/projects/4247/views/1?filterQuery=label%3A%22github+advanced+security%22+label%3Acodeql) to see when support for these new versions will officially land in CodeQL.

That being said, having looked at the logs you linked to, the root failure there isn't due to CodeQL's current lack of support for .NET 8, but because .NET 8 is not installed on the runner. You will need to add a [`setup-dotnet` step](https://github.com/actions/setup-dotnet) to your workflow to install the version of .NET you wish to use. I can't guarantee that this will fix things for you if there are any further issues down the line, but it should at least resolve the issue you are currently encountering.

**Comment by alex289** [comment]
Hey @mbg,
thanks for the fast response. Adding the setup-dotnet step fixed my issue.

Thanks a lot for the help and the good work ❤️
