### ISSUE TITLE
Question: How do I reinitialize/delete a CodeQL database for a language?

### ISSUE THREAD

**Issue by rzuckerm** [github/codeql-action#2609]
In [this repo's security status for CodeQL](https://github.com/TheRenegadeCoder/sample-programs/security/code-scanning/tools/CodeQL/status) there is an extra C++ file that accidentally got scanned in. I would like to delete or at least reinitialize the database so that I can get rid of that file. How do I do this?

**Comment by rzuckerm** [comment]
I tried deleting the C++ database using [this REST API](https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#delete-a-codeql-database), but it didn't seem to work.

**Comment by aeisenberg** [comment]
The CodeQL Action uses the linguist API to determine which files belong to which language. As you can see from this [search](https://github.com/search?q=repo%3ATheRenegadeCoder%2Fsample-programs%20language%3AC%2B%2B&type=code), `[archive/h/hack/hello-world.hh](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/h/hack/hello-world.hh)` is considered a C++ file even though you delete it as part of the workflow.

Deleting the file doesn't work since linguist looks at the files as they are in the repo, not what you have on disk. Instead, you can try adding a [linguist override](https://github.com/github-linguist/linguist/blob/main/docs/overrides.md).

**Comment by rzuckerm** [comment]
I modified the workflow to [remove the Hack files](https://github.com/TheRenegadeCoder/sample-programs/blob/main/.github/workflows/codeql-analysis.yml#L116-L118) before doing a scan. The problem is that the Hack file is stuck in the database (even after deleting the C++ database).

**Comment by aeisenberg** [comment]
No, the status page tells you that there was an extra file discovered in the repo, but _it is not in the database_. Simply deleting the file before won't change the file counts because of the way linguist works.

**Comment by rzuckerm** [comment]
I added [this](https://github.com/TheRenegadeCoder/sample-programs/blob/main/.gitattributes), and it didn't seem to help.

**Comment by rzuckerm** [comment]
Maybe I need to wait until our repo gets reindexed (or whatever) for this to be fixed
