### ISSUE TITLE
Failed to upload a sarif in a pull request: git call failed. Will calculate the base branch SHA on the server. Error: fatal: bad object

### ISSUE THREAD

**Issue by irios-phorus** [github/codeql-action#2623]
I'm trying to use the action `github/codeql-action/upload-sarif@3` to upload a sarif to github from a pull request.
After doing some research and several attempts, I found out that you need to upload the sarif file with a ref that points to the head branch, so I set the following inputs:
```
ref: refs/heads/${{ github.head_ref || github.ref_name }}
sha: ${{ github.event.pull_request.head.sha }}
```

But after running this action, I end up with the following error:
```
git call failed. Will calculate the base branch SHA on the server. Error: fatal: bad object e314656ba240cdf2878387c32ad505077a114559
Uploading results
Warning: commit not found
Error: commit not found
```
(Action run: https://github.com/phorus-group/vulnerability-analysis-action/actions/runs/12058249298/job/33624578403)

I checked the repo code and found out that it's still trying to use the GITHUB_SHA in this line: https://github.com/github/codeql-action/blob/3d3d628990a5f99229dd9fa1821cc5a4f31b613b/lib/actions-util.js#L142
GITHUB_SHA, in a pull request, is not the same as the one from the head branch's last commit, so I assume this is a bug or at least not the expected behavior.

Just to be clear, I'm assuming this action wasn't made to upload sarif files with a pull request ref and SHA because I already tried to upload one without specifying these inputs (to use the default ones) and ended with this other issue:
```
git call failed. Continuing with commit SHA from user input or environment. Error: fatal: ambiguous argument 'refs/remotes/pull/1/merge': unknown revision or path not in the working tree.
```
(Action run: https://github.com/phorus-group/vulnerability-analysis-action/actions/runs/12058811632/job/33626237630)

Repo with the issue: https://github.com/phorus-group/vulnerability-analysis-action

**Comment by redsun82** [comment]
Hey @Daverlo, could you maybe chime in on this one?

**Comment by Daverlo** [comment]
This is failing in the codeql-action itself, so @github/codeql-action-reviewers will know better whats going on.

**Comment by NlightNFotis** [comment]
I'm looking at it on behalf of the above team.

**Comment by NlightNFotis** [comment]
Hello @irios-phorus ,

Thank you for your patience while we were investigating this.

Our understanding is that the initial workflow (`.github/workflows/verify.yml`) is cloning a different project (`phorus/mapper`), which subsequently is being used for analysis. When the `SHA` is being used in the action, it corresponds to a git ref from a different repository (the one the current action is running under, `phorus/vulnerability-analysis-action`), compared to the repo on which the analysis is being run (under `phorus/mapper`), hence when trying to checkout the commit with the given hash, the checkout fails (because the hash denotes a commit not present under this repository).


Do you agree with this assessment?

If so, this isn't supported by the `codeql-action` - it's built with the assumption that the SARIF file being uploaded has been produced by the repository it's running under.

There are however a couple of workarounds you could try to achieve the same end result:
 
1. You could run the action from a different repository, so that when it tries to find a reference to the code in the current checkout it succeeds, or
2. You could use the REST API endpoint for uploading SARIF files to the GitHub REST API. Documentation for that is available here: https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#upload-an-analysis-as-sarif-data
3. Another option, but perhaps messier than the above, could also be trying to upload results using the `codeql github upload-results` tool: https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/github-upload-results

Of all of the above options, `#2` is perhaps the easiest one to achieve.

Is the above helpful for you?

**Comment by irios-phorus** [comment]
He @NlightNFotis

The verify workflow is just being used to test the action in the same way it would be used in another repository, but even then, that repo (https://github.com/phorus-group/mapper) doesn't have a commit with the SHA mentioned in the error message.

It may also be important to note that the `GITUHB_SHA` is set, according to the [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#:~:text=github.com.-,github.sha,-string), based on the `The commit SHA that triggered the workflow.`. That's also why the `actions/checkout` has a section that specifies how to check out the head branch commit instead of the merge commit: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit

That's why I think the issue is caused because:
> The GITHUB_REF for pull_request event is PR **merge** branch refs/pull/:prNumber/merge. And the GITHUB_SHA is the last merge commit on the GITHUB_REF branch. This GITHUB_SHA does not exist in any current branch in the repo. So you will get `fatal: bad object`. 
> \- https://github.com/orgs/community/discussions/26325

So, the SHA doesn't point to an existing commit in the head branch but to the SHA of the merge commit.

My goal is not to make this verify.yml workflow work but to make sure that the step that uploads the sarif file in my custom action works on the branches regardless of the event that triggered the workflow. I can do it using the API, but I think there should be a way to do it using the `upload-sarif` action, since I am trying to upload a sarif file to the current branch of the current repo (even if, internally, github creates a merge branch with a different sha).

**Comment by aeisenberg** [comment]
I'm unclear what you're trying to do.

When you run the checkout action in a workflow and there is no `ref` input specified, the merge commit is checked out, not the HEAD commit. It's a synthetic commit (meaning that it doesn't actually exist in the repository), but actions uses this because this is the commit that will be created when the PR is merged into main.

In most cases, you should not need to specify `ref` or `sha` for `upload-sarif`. It will determine these values from the environment. But, this only works if you are trying to upload SARIF created from the repository that owns the workflow and to that same repository in github.

If you want to analyze the HEAD commit (not recommended), you need to explicitly check it out (using the instructions you linked to) and set the action inputs appropriately.

In general, you cannot upload sarif to a repo that did not generate the sarif. If you are still having problems, please share a workflow that uploads to the same repo.

**Comment by irios-phorus** [comment]
I'm not trying to upload a sarif to the test repository, I'm just "stealing" the code from that repository to run trivy and get a vulnerability analysis report, and thus validate that my custom action for vulnerability analysis works as expected.
I'm not trying to upload a sarif file to a different repo, I'm just trying to upload a sarif file generated in a pull request event to the right branch.

Let's recap:
- I already tried to make that verify workflow work by not specifying the ref and sha inputs, but it fails because it was triggered by a pull request event:
```
git call failed. Continuing with commit SHA from user input or environment. Error: fatal: ambiguous argument 'refs/remotes/pull/1/merge': unknown revision or path not in the working tree.
```
- I then specified the ref and sha inputs to point to the head branch instead of the synthetic merge commit, but the upload sarif action [still failed](https://github.com/phorus-group/vulnerability-analysis-action/actions/runs/12058249298/job/33624578403) with a sha that was not the same as the one provided in the input:
```
Run echo "github.sha - e314656ba240cdf2878387c32ad505077a114559"
github.sha - e314656ba240cdf2878387c32ad505077a114559
github.event.pull_request.head.sha - e3c6f64c7484204b85a8f5155069ad566f68e0b7
github.event.pull_request.base.sha - ffa286640de9d88c5ad051f15ff9fd9e501e0281
github.event.workflow_run.head_sha - 
Run github/codeql-action/upload-sarif@v3
Uploading results
  Processing sarif files: ["vulnerability-report.sarif"]
  Validating vulnerability-report.sarif
  Combining SARIF files using the CodeQL CLI
  Adding fingerprints to SARIF file. See https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs for more information.
  git call failed. Will calculate the base branch SHA on the server. Error: fatal: bad object e314656ba240cdf2878387c32ad505077a114559
  
  Uploading results
  Warning: commit not found
  Error: commit not found
```

Is this an expected behavior? And if so, why?

**Comment by aeisenberg** [comment]
> the action gets confused because I'm checking out a different repository in the current working directory, so it fails and reverts to using the default GITHUB_SHA.

This is exactly the problem as we have been saying. You can only upload sarif for the repository that owns the workflow. All of the other problems flow from that.

Perhaps this needs to be called out explicitly in the documentation and the action.

**Comment by irios-phorus** [comment]
I changed my code to checkout the test repository in another directory instead of using the work dir and the problem disappeared.

It might be useful to add this to the documentation explicitly, as I assumed that the upload-sarif action only used the API, the GITHUB_TOKEN, and the sarif file, and the limitation with other repos was because the GITHUB_TOKEN doesn't have access to other repos by default. The [current documentation fuels](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github) this assumption as it mentions the API and the upload-sarif action as equivalents: `SARIF files can be uploaded to a repository using the API or GitHub Actions`

**Comment by irios-phorus** [comment]
Closing the issue
