### ISSUE TITLE
'Fail if issues found' functionality

### ISSUE THREAD

**Issue by LebedevRI** [github/codeql-action#304]
This might be a documentation issue, but i did not find anything relevant in the docs.

Right now, as far as i can tell, the results of CodeQL scan are only displayed in
the Code scanning alerts tab of repository's Security tab.
As far as i can see, presence of said issues does not get displayed as a status check on a commit.

While having CodeQL results as a commit status would be an improvement,
i would however _like_ to have an even more aggressive option:
would it be possible for the Actions job that run CodeQL scan to fail, if any issues are found?

It is widely available elsewhere - `-Werror` for clang/gcc, `--warnings-as-errors=` for clang-tidy,
`--status-bugs` for clang static analyzer `scan-build` wrapper,
and is a default mode for [Ericsson's CodeChecker](https://github.com/Ericsson/codechecker/pull/2943).

**Comment by robertbrignull** [comment]
CodeQL results are displayed as a check run on a PR if you have the code scanning workflow set up to analyse pull requests (note you also have to be analysing all commits on the base branch). The annotations from this should also show up in the code on the files tab. They look like https://github.com/github/codeql-action/pull/301/checks?check_run_id=1390874683

Unfortunately it's not possible to make the actions run that runs CodeQL to fail. This is because code scanning in the background is comparing the results from the scan on the PR to the scan from the base branch, and thus we only know if results are introduced after the actions run has finished. Hence why we create this extra new check run to show the results in.

Currently it only marks the check run as failed for alerts that are marked as errors. The ability to treat warnings as errors is a something we're working on adding, so there's more customisation of the behaviour there.

I hope that answers your question. I'm going to close this because I think I've answered and the feature of having warnings as errors is something we already have tracked internally. If you have other questions please do say.
