### ISSUE TITLE
List of possible alert.rule.description values

### ISSUE THREAD

**Issue by aleks-ivanov** [github/codeql-action#382]
An example GET to the Code Scanning Alerts REST API, looks like this:

```
 {
    "number": 310,
    "created_at": "2021-01-05T14:39:08Z",
    "url": "https://api.github.com/repos/owner/project/code-scanning/alerts/310",
    "html_url": "https://github.com/owner/project/security/code-scanning/310",
    "state": "open",
    "dismissed_by": null,
    "dismissed_at": null,
    "dismissed_reason": null,
    "rule": {
      "id": "cs/linq/inconsistent-enumeration",
      "severity": "warning",

      "description": "Bad multiple iteration"

    },
    "tool": {
      "name": "CodeQL"
    }
  }
```

I would like to know, what are all the possible values for the property **description**, that CodeQL generates and assigns, and the conditions to determine each one ?

**Comment by adityasharad** [comment]
Hello @AleksIvanovSinglet. The `rule.description` property for Code Scanning alerts produced by CodeQL is currently taken from the [`@name` metadata field](https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/#metadata-properties) in the corresponding CodeQL query that produced the alert. (This may change in future.)

For example, the query that produced the alert above has the ID `cs/linq/inconsistent-enumeration`, which you can [see here in the `github/codeql` repo](https://github.com/github/codeql/blob/047cd2b706610bb06f2b9be4543258ba9a47bec2/csharp/ql/src/Linq/BadMultipleIteration.ql#L2).

You can browse all the open-source queries in the `github/codeql` and `github/codeql-go` repos, and see their names in the query metadata section at the top of each query file.

If you wanted to programmatically generate a list of names, you could use the [CodeQL CLI](https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/): `codeql resolve queries <path to github/codeql>/ql/csharp/ql/src/codeql-suites/csharp-code-scanning.qls` followed by `codeql resolve metadata --format json <query file>` on each file path it returns will give you the query metadata for each query.

Note that such a list of all the available values would quickly become out of date, because we are continuously expanding our set of queries, and because the human-readable names are not guaranteed to be stable.

**Comment by AleksIvanovSinglet** [comment]
Thank you!
