### ISSUE TITLE
Hidden directories in VS Code

### ISSUE THREAD

**Issue by RA80533** [github/codeql-action#485]
[settings.json](https://github.com/github/codeql-action/blob/f00bafbde1cf72f723cff6bcb0fa170325b2edb9/.vscode/settings.json) declares a few directories to exclude from the explorer view in VS Code. Without prior understanding of this functionality, it will not be apparent to prospective developers as to why these directories are not visible in-editor. The lib directory, for example, is visible on the repository page but not in the editor.

Is there a strong enough reason to exclude such directories from being seen?

**Comment by robertbrignull** [comment]
I believe the main reason those were excluded was less about showing up in the file browser part of the editor and more due to javascript files showing up in search results. When searching for something (e.g. a variable or function name) you almost certainly only want typescript results and having everything be duplicated by an extra match in the javascript was annoying.

You are right though there isn't much explanation as to why those files are excluded. Thankfully that json file allows comments so we could add some better reasoning there.

I would argue that we do still want to exclude those files. Unless you've investigating a particular kind of bug, there's almost no reason to look at the javascript files.

**Comment by aeisenberg** [comment]
>  I suspect the reason it's not untracked has to do with the GitHub Actions platform itself. Am I misled in my assumption?

That's right. I made a change to the contributing guide to better explain why.

> Would it be better to change `files.exclude` to `search.exclude`?

I prefer having the `lib` folder hidden. It has been this way since before I joined this project. If there are any committers who feels differently, then that's something we can discuss.
