### ISSUE TITLE
Add examples using Cache action?

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql-action#56]
It appears some of the actions provided by this repository can take quite some time:
- `codeql-action/init`: Downloads 1GB archive, taking ~1 minute
- `codeql-action/autobuild`: Downloads all required dependencies necessary for building the project (e.g. Maven dependencies)

Would it therefore make sense to use the [Cache action](https://github.com/marketplace/actions/cache)? If so, could you add that to the README (and to the workflow file GitHub adds when pressing "Set up code scanning"?) please.

### `codeql-action/init`
Note that the Cache action has limitations on the cache size (currently [5GB per repository](https://github.com/marketplace/actions/cache#cache-limits)), so maybe due to the large size of the releases this would reach the Cache limit too soon.
Also the releases are already compressed as `.tar.gz`, so the Cache action (which just compresses the files as well) might not actually cause any speed up.

### `codeql-action/autobuild`
Since this action supports multiple programming languages, the location of the dependencies differs, so I am not sure how a Cache example could cover all (or at least multiple) of them in a reasonable way.
Maybe it would at least be helpful to link in the README to the [Cache examples](https://github.com/marketplace/actions/cache#implementation-examples).

**Comment by robertbrignull** [comment]
Thanks for the observations. You're absolutely right it can be a bit slow at times.

Due to the cache size limits I think that use of the cache has to always to a user choice. We don't want to put multiple GB into the cache and cause problems for other actions/workflows.

Currently I'm not sure if it's possible to utilize the cache in speeding up downloading and unpacking CodeQL. That's something that could be looked into.

For storing build dependencies this is always going to be repository specific so there's not much we can do except point out the existence of the cache with a link. I agree we could add something like that into the readme in the example workflow. However it would still require user involvement to set up and get it working correctly. There are also certain pitfalls that a user could fall into, for example if you cache the build artefacts such that the code is not build from scratch each time then not all code will be extracted and the analysis results will not be correct. We'd have to be careful to not encourage people into these problems.

**Comment by jhutchings1** [comment]
Thanks for your feedback. This is definitely great feedback. We're looking at what we can do to reduce the latency with the initialization in the near future. I don't think we're going to prioritize further caching in the immediate term, though. I'm closing for now, but thank you again!
