### ISSUE TITLE
Excessive API call usage

### ISSUE THREAD

**Issue by anomiex** [github/codeql-action#567]
It appears that the recommended configuration for this action will make 11 calls to the GitHub REST API per push and per language, which can add up quickly and make it too easy to reach the rate limit of 1000 calls per hour with the default Actions token.

* [`getWorkflowPath()`](https://github.com/github/codeql-action/blob/cbdf0df97be3a7cc448a09cf1a4d219c09aec646/src/actions-util.ts#L341-L361) makes two calls, and seems to be called twice from github/codeql-action/init@v1.
  * It looks like one is [constructing a cache key](https://github.com/github/codeql-action/blob/cbdf0df97be3a7cc448a09cf1a4d219c09aec646/src/actions-util.ts#L389-L392) like ".github/workflows/filename.yml:jobid".
  * The other seems to be [linting the job definition?](https://github.com/github/codeql-action/blob/cbdf0df97be3a7cc448a09cf1a4d219c09aec646/src/actions-util.ts#L189-L284)
* github/codeql-action/init@v1 then makes two calls to update the status.
* github/codeql-action/autobuild@v1 also makes two calls to update the status.
* github/codeql-action/analyze@v1 makes another two calls to update the status, plus one more in between to actually upload the results.

I'd expect just two or three calls to actually be needed: one (maybe) to update the status to "working" at the start, one to upload the results, and one to update the status to "completed" at the end.

If the cache key and linting are needed, could you convince the Actions team to supply the workflow file path via an [environment variable](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables) or [context property](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) so you don't have to make two API calls to fetch it? It looks like they already conditionally provide this information in `github.workflow` (and maybe also `GITHUB_WORKFLOW`) if the workflow yaml file doesn't name the workflow itself.

FYI, this came up when I was working with GitHub Developer Support to try to figure out why we kept hitting the API rate limits, and I noticed that this action was responsible for a significant fraction of the calls. The support person suggested I report it to you directly.

**Comment by aeisenberg** [comment]
Thanks for raising this issue. We haven't put much effort into minimizing API calls since this is the first we've heard that it can be a problem. With this in mind, we're doing a review of all the calls and seeing if there are some that can be dropped or merged.

With that in mind, are you running the code scanning workflow on every push to any branch? Our recommended setup is to run on push to the default branch, and also on pull request.

**Comment by anomiex** [comment]
No. We're running it on pushes to master, pull requests targeting master, and a weekly cron. But since most of our pull requests target master and most of our pushes are updating PRs, that still winds up running on most pushes.

You can see our workflow yourself [here](https://github.com/Automattic/jetpack/blob/master/.github/workflows/codeql-analysis.yml).

P.S. You may want to review your documentation at https://github.com/github/codeql-action#usage, it shows a configuration that does run on every push and PR.

**Comment by chrisgavin** [comment]
Hi @anomiex. We've made some changes to how our API rate limiting works that should hopefully help here. Specifically, calls to update the analysis status are fairly cheap so we have decided to exclude them from the normal API rate limiting. I hope this helps lessen the concern about CodeQL Action requests using up too much of the rate limit quota for your Actions token.

Hopefully we can also make more improvements in this regard in future; as you've suggested, having the workflow file available on the runner rather than having to fetch it from the API would seem very useful.

**Comment by jsoref** [comment]
Fwiw, the fact that `github.workflow` is [unreliable](https://docs.github.com/en/actions/learn-github-actions/environment-variables) is a real [thorn in my side](https://github.com/check-spelling/check-spelling/blob/8e5f1a5eb8b1cf0da26fe3def6e3229d1cf0c6b9/unknown-words.sh#L319-L331). It'd be really nice if this team could tell the actions team that it should be published as a reliable variable ([`GITHUB_WORKFLOW_PATH`](https://docs.github.com/en/actions/learn-github-actions/environment-variables#naming-conventions-for-environment-variables)) so that the rest of us could benefit from not having to beg.

**Comment by adityasharad** [comment]
Thanks for the feedback: as I understand it, the request is to expose an Actions context value and environment variable that consistently returns the full path to the workflow file within the repo, unlike `github.workflow`/`GITHUB_WORKFLOW` which returns the workflow name if there is one and the file path otherwise. We'll pass that on.

We have no further planned work on reducing API call usage after https://github.com/github/codeql-action/issues/567#issuecomment-870409715, and will remain careful to avoid introducing unnecessary API call overhead in future. With that in mind, I am closing this issue, but please file fresh issues for us if you encounter further trouble with API limits and we will be happy to investigate.
