### ISSUE TITLE
BUG: Fixed findings are not automatically removed from scanning dashboard

### ISSUE THREAD

**Issue by laurentsimon** [github/codeql-action#814]
Please see this finding in my test repo https://github.com/laurentsimon/scorecard-action-test-4/security/code-scanning/14?query=ref%3Arefs%2Fheads%2Fmain

It shows `Fixed in branch main with commit 356ddd2 X minutes ago`. Yet, the finding is still marked as `open`.

Is there something wrong with my SARIF files or something in the way you process them or something else?

The commit that crated the finding is https://github.com/laurentsimon/scorecard-action-test-4/actions/runs/1436013685
The commit that fixed it is https://github.com/laurentsimon/scorecard-action-test-4/actions/runs/1436079297

Advice appreciated, thanks!

**Comment by aeisenberg** [comment]
The reason why the alert has not been closed is that the commit that fixed it is using a different category than the one that introduced it. If you want the alert closed, you will need to ensure the category remains the same.

I know you are discussing something related at https://github.com/github/codeql-action/issues/810. 

If you do decide to use multiple categories (one complete, and one partial), you will need to ensure that they run consistently. 

I will close this issue since it seems like everything is behaving as expected and we can continue the discussion on #810.
