### ISSUE TITLE
Can I scan my code without building?

### ISSUE THREAD

**Issue by mcfriend99** [github/codeql-action#921]
Having to build a large codebase just to run CodeQL is a waste of resource and time. Just wandering if it's possible to run CodeQL in the workflows without having to build the code. This should be a faster and better experience.

**Comment by aeisenberg** [comment]
For compiled languages, unfortunately, this is not possible. In order to determine how the program is structured, the CodeQL extractor needs to hook into the compilation process so that it can see _exactly_ what the compiler sees. There is no other way.

A recommendation that I have is to structure your analysis so that it is doing as little as possible other than compiling code. For example, if downloading dependencies takes too much time, you can use the [`actions/cache` action](https://github.com/github/codeql-action/issues/921). Or if you have a mono-repo, you can split it up so that different jobs will each analyze a portion of the repository.
